"""
Blender 5.0 export for surface_mesh.
Generates a Blender project with mesh showcase: dark background, spot lights,
mildly reflective material, and water reflection.
"""

import os
import subprocess
import sys
import numpy as np


def _generate_blender_script(vertices, faces, blend_path, mesh_name="SurfaceMesh"):
    """Generate a Blender Python script that creates the showcase scene (Blender 5.0+)."""
    blend_path = os.path.abspath(blend_path)
    blend_path_repr = repr(blend_path)
    # Serialize mesh data for embedding in script
    verts_str = repr(vertices.tolist())
    faces_str = repr(faces.tolist())

    script = f'''"""
Blender 5.0 showcase scene - auto-generated by pySHP surface_mesh.export_blender()
Run with: blender --background --python "{os.path.basename(blend_path).replace('.blend', '_setup.py')}"
"""

import bpy
import math

# Mesh data
verts = {verts_str}
faces = {faces_str}

# Clear default scene
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)

# Create mesh object
mesh_data = bpy.data.meshes.new("{mesh_name}_data")
mesh_data.from_pydata(verts, [], faces)
mesh_data.update()

mesh_obj = bpy.data.objects.new("{mesh_name}", mesh_data)
bpy.context.collection.objects.link(mesh_obj)
bpy.context.view_layer.objects.active = mesh_obj
mesh_obj.select_set(True)

# Center and scale mesh for nice display
bbox = [mesh_obj.bound_box[i] for i in range(8)]
xs = [v[0] for v in bbox]
ys = [v[1] for v in bbox]
zs = [v[2] for v in bbox]
center_x = (max(xs) + min(xs)) / 2
center_y = (max(ys) + min(ys)) / 2
center_z = (max(zs) + min(zs)) / 2
size = max(max(xs)-min(xs), max(ys)-min(ys), max(zs)-min(zs)) or 1.0
scale = 2.0 / size

mesh_obj.location = (-center_x * scale, -center_y * scale, -center_z * scale + 1.5)
mesh_obj.scale = (scale, scale, scale)
bpy.ops.object.transform_apply(location=True, scale=True)

# Mildly reflective material for mesh (Principled BSDF)
mat_mesh = bpy.data.materials.new(name="Mesh_Reflective")
mat_mesh.use_nodes = True
nodes = mat_mesh.node_tree.nodes
nodes.clear()
bsdf = nodes.new(type='ShaderNodeBsdfPrincipled')
bsdf.location = (0, 0)
output = nodes.new(type='ShaderNodeOutputMaterial')
output.location = (300, 0)
mat_mesh.node_tree.links.new(bsdf.outputs['BSDF'], output.inputs['Surface'])

# Soft metallic look with mild reflection: base color, low roughness, slight metallic
bsdf.inputs['Base Color'].default_value = (0.72, 0.78, 0.85, 1.0)  # Soft blue-gray
bsdf.inputs['Roughness'].default_value = 0.25
bsdf.inputs['Metallic'].default_value = 0.15
bsdf.inputs['Specular IOR Level'].default_value = 0.8

mesh_obj.data.materials.append(mat_mesh)

# Water plane - large flat plane below mesh
bpy.ops.mesh.primitive_plane_add(size=50, location=(0, 0, 0))
water_plane = bpy.context.active_object
water_plane.name = "Water"

# Reflective water material
mat_water = bpy.data.materials.new(name="Water_Reflective")
mat_water.use_nodes = True
wnodes = mat_water.node_tree.nodes
wnodes.clear()
w_bsdf = wnodes.new(type='ShaderNodeBsdfPrincipled')
w_bsdf.location = (0, 0)
w_output = wnodes.new(type='ShaderNodeOutputMaterial')
w_output.location = (300, 0)
mat_water.node_tree.links.new(w_bsdf.outputs['BSDF'], w_output.inputs['Surface'])

# Water: dark blue-green, very reflective, low roughness
w_bsdf.inputs['Base Color'].default_value = (0.02, 0.08, 0.12, 1.0)
w_bsdf.inputs['Roughness'].default_value = 0.02
w_bsdf.inputs['Metallic'].default_value = 0.0
w_bsdf.inputs['Specular IOR Level'].default_value = 1.0
w_bsdf.inputs['Transmission Weight'].default_value = 0.3
w_bsdf.inputs['Alpha'].default_value = 0.9

water_plane.data.materials.append(mat_water)

# Spot lights around the shape
light_positions = [
    (5, 5, 8),
    (-5, 4, 7),
    (3, -6, 6),
    (-4, -3, 5),
]
for i, pos in enumerate(light_positions):
    bpy.ops.object.light_add(type='SPOT', location=pos)
    spot = bpy.context.active_object
    spot.name = "Spot_%d" % (i+1)
    spot.data.energy = 400
    spot.data.spot_size = math.radians(60)
    spot.data.spot_blend = 0.3
    # Track toward mesh center
    constraint = spot.constraints.new(type='TRACK_TO')
    constraint.target = mesh_obj
    constraint.track_axis = 'TRACK_NEGATIVE_Z'
    constraint.up_axis = 'UP_Y'

# Camera - front-right view
bpy.ops.object.camera_add(location=(6, 5, 5))
camera = bpy.context.active_object
camera.name = "Camera"
# Point camera at mesh
track = camera.constraints.new(type='TRACK_TO')
track.target = mesh_obj
track.track_axis = 'TRACK_NEGATIVE_Z'
track.up_axis = 'UP_Y'
bpy.context.scene.camera = camera

# Dark world background
world = bpy.data.worlds.get("World") or bpy.data.worlds.new("World")
bpy.context.scene.world = world
world.use_nodes = True
nodes_w = world.node_tree.nodes
# Get or create World Output and Background
out_node = None
for n in nodes_w:
    if n.type == 'OUTPUT_WORLD':
        out_node = n
        break
if out_node is None:
    out_node = nodes_w.new(type='ShaderNodeOutputWorld')
bg = nodes_w.get("Background")
if bg is None:
    bg = nodes_w.new(type='ShaderNodeBackground')
    world.node_tree.links.new(bg.outputs['Background'], out_node.inputs['Surface'])
bg.inputs['Color'].default_value = (0.02, 0.02, 0.04, 1.0)
bg.inputs['Strength'].default_value = 0.1

# Use Cycles for reflections
bpy.context.scene.render.engine = 'CYCLES'
bpy.context.scene.cycles.samples = 128

# Save
blend_path = {blend_path_repr}
bpy.ops.wm.save_as_mainfile(filepath=blend_path)
print("Blender project saved to:", blend_path)
'''
    return script


def export_blender(mesh, filename, script_path=None, run_blender=False, blender_executable=None):
    """
    Export surface_mesh to a Blender 5.0 project with showcase scene.

    Creates a Python script that, when run inside Blender, builds a scene with:
    - The mesh object with mildly reflective material
    - Dark background
    - Spot lights illuminating the shape
    - Reflective water plane that the shape hovers above

    Parameters
    ----------
    mesh : surface_mesh
        The mesh to export (must have .X and .F attributes).
    filename : str
        Output path for the .blend file.
    script_path : str, optional
        Path for the generated Blender Python script. Default: same directory
        as filename, with suffix '_blender_setup.py'.
    run_blender : bool, optional
        If True, attempt to run Blender to generate the .blend file.
        Requires Blender to be installed and in PATH (or blender_executable).
    blender_executable : str, optional
        Path to Blender executable. If None, uses 'blender' from PATH.

    Returns
    -------
    script_path : str
        Path to the generated Python script.

    Notes
    -----
    To generate the .blend file, run:
        blender --background --python <script_path>

    Or set run_blender=True when Blender is installed.
    """
    X = mesh.X
    F = mesh.F

    if F.shape[0] == 3 and F.shape[1] != 3:
        F = F.T
    if X.shape[0] == 3 and X.shape[1] != 3:
        X = X.T

    # Ensure triangular faces
    if F.shape[1] == 4:
        # Quad to tri: 0,1,2 and 0,2,3
        F1 = F[:, [0, 1, 2]]
        F2 = F[:, [0, 2, 3]]
        F = np.vstack([F1, F2])

    filename = os.path.abspath(filename)
    if not filename.lower().endswith('.blend'):
        filename += '.blend'

    if script_path is None:
        base = os.path.splitext(filename)[0]
        script_path = base + '_blender_setup.py'
    script_path = os.path.abspath(script_path)

    script = _generate_blender_script(X, F, filename)

    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(script)

    if run_blender:
        blender_cmd = blender_executable or 'blender'
        try:
            result = subprocess.run(
                [blender_cmd, '--background', '--python', script_path],
                capture_output=True,
                text=True,
                timeout=120,
            )
            if result.returncode != 0:
                sys.stderr.write(f"Blender stderr: {result.stderr}\n")
            if result.returncode == 0 and os.path.exists(filename):
                print(f"Blender project saved: {filename}")
            else:
                print(f"Script written to {script_path}. Run manually: {blender_cmd} --background --python {script_path}")
        except FileNotFoundError:
            print(f"Blender not found. Run manually: blender --background --python {script_path}")
        except subprocess.TimeoutExpired:
            print(f"Blender timed out. Script: {script_path}")

    return script_path
